const tips=[
    "Minum air putih minimal 8 gelas sehari",
    "Bangun dan tidur di jam yang teratur",
    "Konsumsi buah dan sayur setiap hari",
    "Hindari begadang tanpa alasan penting",
    "Kurangi makanan cepat saji",
    "Jangan melewatkan sarapan",
    "Olahraga minimal 30 menit sehari",
    "Lakukan peregangan setelah bangun tidur",
    "Jangan terlalu lama duduk",
    "Jaga postur tubuh saat duduk",
    "Cuci tangan sebelum dan sesudah makan",
    "Hindari menyentuh wajah dengan tangan kotor",
    "Batasi konsumsi gula berlebihan",
    "Kurangi minuman bersoda",
    "Perbanyak konsumsi serat",
    "Jaga kebersihan gigi dan mulut",
    "Sikat gigi dua kali sehari",
    "Ganti sikat gigi setiap 3 bulan",
    "Gunakan tabir surya saat keluar rumah",
    "Hindari paparan sinar matahari berlebihan",
    "Jaga berat badan ideal",
    "Kurangi konsumsi garam",
    "Hindari merokok",
    "Jauhi asap rokok",
    "Jangan konsumsi alkohol berlebihan",
    "Istirahat jika tubuh terasa lelah",
    "Kelola stres dengan baik",
    "Lakukan meditasi atau relaksasi",
    "Bersosialisasilah dengan orang terdekat",
    "Jangan pendam emosi negatif",
    "Laugh more and stress less",
    "Dengarkan musik yang menenangkan",
    "Luangkan waktu untuk diri sendiri",
    "Rutin cek kesehatan",
    "Periksa tekanan darah secara berkala",
    "Periksa kadar gula darah",
    "Jaga kesehatan jantung",
    "Perbanyak berjalan kaki",
    "Gunakan tangga daripada lift jika memungkinkan",
];

function generateTip(){
    constrandom = Math.floor(Math.random()*tips.length);
    document.getElementById("dailyTip").innerText = tips[random];
}
window.onload = generateTip;