const tips = [
  "Minum air putih minimal 8 gelas sehari",
  "Bangun dan tidur di jam yang teratur",
  "Hindari begadang tanpa alasan penting",
  "Konsumsi buah dan sayur setiap hari",
  "Kurangi makanan cepat saji",
  "Jangan melewatkan sarapan",
  "Olahraga minimal 30 menit sehari",
  "Lakukan peregangan setelah bangun tidur",
  "Jangan terlalu lama duduk",
  "Jaga postur tubuh saat duduk",
  "Cuci tangan sebelum dan sesudah makan",
  "Hindari menyentuh wajah dengan tangan kotor",
  "Batasi konsumsi gula berlebihan",
  "Kurangi minuman bersoda",
  "Perbanyak konsumsi serat",
  "Jaga kebersihan gigi dan mulut",
  "Sikat gigi dua kali sehari",
  "Ganti sikat gigi setiap 3 bulan",
  "Gunakan tabir surya saat keluar rumah",
  "Hindari paparan sinar matahari berlebihan",
  "Jaga berat badan ideal",
  "Kurangi konsumsi garam",
  "Hindari merokok",
  "Jauhi asap rokok",
  "Jangan konsumsi alkohol berlebihan",
  "Istirahat jika tubuh terasa lelah",
  "Kelola stres dengan baik",
  "Lakukan meditasi atau relaksasi",
  "Bersosialisasilah dengan orang terdekat",
  "Jangan pendam emosi negatif",
  "Laugh more and stress less",
  "Dengarkan musik yang menenangkan",
  "Luangkan waktu untuk diri sendiri",
  "Rutin cek kesehatan",
  "Periksa tekanan darah secara berkala",
  "Periksa kadar gula darah",
  "Jaga kesehatan jantung",
  "Perbanyak berjalan kaki",
  "Gunakan tangga daripada lift jika memungkinkan",
  "Jangan menunda ke toilet",
  "Hindari menahan buang air kecil",
  "Perbanyak makanan yang mengandung omega-3",
  "Kurangi lemak jenuh",
  "Makan secara perlahan",
  "Jangan makan berlebihan",
  "Jangan langsung tidur setelah makan",
  "Minum air hangat di pagi hari",
  "Detoks tubuh dengan pola makan sehat",
  "Hirup udara segar setiap pagi",
  "Bersihkan lingkungan sekitar",
  "Jaga kebersihan kamar",
  "Ganti sprei secara rutin",
  "Jemur bantal dan kasur",
  "Hindari penggunaan gadget berlebihan",
  "Istirahatkan mata setiap 20 menit",
  "Gunakan kacamata anti radiasi",
  "Jangan membaca dalam gelap",
  "Perbanyak tawa",
  "Jaga kesehatan mental",
  "Hargai diri sendiri",
  "Terima kekurangan diri",
  "Jaga pola makan seimbang",
  "Kunyah makanan dengan baik",
  "Hindari makanan mentah yang tidak higienis",
  "Cuci bahan makanan sebelum dikonsumsi",
  "Simpan makanan dengan benar",
  "Gunakan masker saat sakit",
  "Minum vitamin bila diperlukan",
  "Konsultasi ke dokter jika sakit",
  "Jangan minum obat sembarangan",
  "Gunakan obat sesuai resep",
  "Jangan berbagi alat makan",
  "Hindari dehidrasi",
  "Minum air setelah bangun tidur",
  "Lakukan stretching saat bekerja",
  "Duduk dengan posisi tegak",
  "Gunakan kursi yang nyaman",
  "Atur pencahayaan ruangan",
  "Jangan terlalu sering minum kopi",
  "Kurangi konsumsi kafein",
  "Perbanyak makanan berprotein",
  "Konsumsi karbohidrat secukupnya",
  "Makan tepat waktu",
  "Perbanyak aktivitas fisik",
  "Berjemur di pagi hari",
  "Periksa mata secara rutin",
  "Gunakan kacamata sesuai resep",
  "Latih pernapasan dalam",
  "Perbanyak senyum",
  "Jaga pikiran tetap positif",
  "Jangan membandingkan diri dengan orang lain",
  "Bersyukur setiap hari",
  "Percaya diri",
  "Ciptakan lingkungan sehat",
  "Jaga hubungan sosial yang baik",
  "Bergerak lebih banyak daripada duduk",
];

function generateTip() {
  const random = Math.floor(Math.random() * tips.length);
  document.getElementById("dailyTip").innerText = tips[random];
}
window.onload = generateTip;
